### ISSUE TITLE
Segfault in SLAdvect::advect

### ISSUE THREAD

**Issue by n16h7hunt3r** [FireDynamics/ARTSS#12]
cmd
```
../build/bin/artss_serial -l info -o - Test_NavierStokesTurb_FlowAroundCube_BoundaryHandling.xml
```

truncated output
```
[2020-03-27 09:01:03.503] [info] t_cur=0.16
[2020-03-27 09:01:03.503] [info] Advect ...
[2020-03-27 09:01:03.960] [info] Calculating Turbulent viscosity ...
[2020-03-27 09:01:04.033] [info] Diffuse ...
[2020-03-27 09:01:10.950] [info] Number of iterations: 100
[2020-03-27 09:01:10.950] [info] Jacobi ||res||=144.04791452519288
[2020-03-27 09:01:18.095] [info] Number of iterations: 100
[2020-03-27 09:01:18.095] [info] Jacobi ||res||=3688.9205075300506
[2020-03-27 09:01:25.161] [info] Number of iterations: 100
[2020-03-27 09:01:25.161] [info] Jacobi ||res||=79.38827260185163
[2020-03-27 09:01:25.328] [info] Pressure ...
[2020-03-27 09:01:29.431] [info] t_cur=0.17
[2020-03-27 09:01:29.431] [info] Advect ...

Program received signal SIGSEGV, Segmentation fault.
[----------------------------------registers-----------------------------------]
RAX: 0x117f0f3 
RBX: 0x7fffef584010 --> 0x3fdb42770b798dcb 
RCX: 0x68 ('h')
RDX: 0x84096f 
RSI: 0x117f0f2 
RDI: 0x886310 
RBP: 0x102 
RSP: 0x7fffffffdbd0 --> 0x1 
RIP: 0x55555558b2dc (<_ZN8SLAdvect6advectEP5FieldS1_PKS0_S3_S3_b+1564>:	movsd  xmm13,QWORD PTR [rbx+rsi*8])
R8 : 0x7fff7ce3fcf8 --> 0x4b7b20 (' {K')
R9 : 0x8304 
R10: 0x101 
R11: 0x81 
R12: 0x101 
R13: 0x4b7b1f 
R14: 0x11c4a94 
R15: 0x11c4a95
EFLAGS: 0x10212 (carry parity ADJUST zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x55555558b2ce <_ZN8SLAdvect6advectEP5FieldS1_PKS0_S3_S3_b+1550>:	mulsd  xmm3,xmm1
   0x55555558b2d2 <_ZN8SLAdvect6advectEP5FieldS1_PKS0_S3_S3_b+1554>:	mulsd  xmm0,xmm12
   0x55555558b2d7 <_ZN8SLAdvect6advectEP5FieldS1_PKS0_S3_S3_b+1559>:	addsd  xmm3,xmm13
=> 0x55555558b2dc <_ZN8SLAdvect6advectEP5FieldS1_PKS0_S3_S3_b+1564>:	movsd  xmm13,QWORD PTR [rbx+rsi*8]
   0x55555558b2e2 <_ZN8SLAdvect6advectEP5FieldS1_PKS0_S3_S3_b+1570>:	mulsd  xmm13,xmm2
   0x55555558b2e7 <_ZN8SLAdvect6advectEP5FieldS1_PKS0_S3_S3_b+1575>:	mulsd  xmm3,xmm11
   0x55555558b2ec <_ZN8SLAdvect6advectEP5FieldS1_PKS0_S3_S3_b+1580>:	mulsd  xmm2,QWORD PTR [rbx+r14*8]
   0x55555558b2f2 <_ZN8SLAdvect6advectEP5FieldS1_PKS0_S3_S3_b+1586>:	addsd  xmm0,xmm3
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffdbd0 --> 0x1 
0008| 0x7fffffffdbd8 --> 0x7ffff378a010 --> 0x3fdb42770b798dcb 
0016| 0x7fffffffdbe0 --> 0x7fffef584010 --> 0x3fdb42770b798dcb 
0024| 0x7fffffffdbe8 --> 0x7fffe2f72010 --> 0x3f683f13fe9c5ff4 
0032| 0x7fffffffdbf0 --> 0x7fffd6960010 --> 0x3f88c09e3eb696fe 
0040| 0x7fffffffdbf8 --> 0x7fff7e9a0a50 --> 0x2207 
0048| 0x7fffffffdc00 --> 0x1 
0056| 0x7fffffffdc08 --> 0x1 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
0x000055555558b2dc in SLAdvect::advect(Field*, Field*, Field const*, Field const*, Field const*, bool) ()
gdb-peda$ bt
#0  0x000055555558b2dc in SLAdvect::advect(Field*, Field*, Field const*, Field const*, Field const*, bool) ()
#1  0x00005555555bf8f7 in NSTurbSolver::DoStep(double, bool) ()
#2  0x00005555555fa0ab in TimeIntegration::run() ()
#3  0x000055555556eb30 in main ()
#4  0x00007ffff79ba023 in __libc_start_main () from /usr/lib/libc.so.6
#5  0x000055555556ed9e in _start ()
```

can confirm?

**Comment by n16h7hunt3r** [comment]
not reproducible

**Comment by n16h7hunt3r** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555588219 in SLAdvect::advect (this=0x555555749550, out=0x55555564e390, in=0x55555564ef50, 
    u_vel=0x55555564ef50, v_vel=0x55555564f850, w_vel=0x5555556508f0, sync=false)
    at /home/user/git/ARTSS/src/advection/SLAdvect.cpp:189
189	                         + t * ((1. - s) * ((1. - r) * d_in[IX(i0, j0, k1, Nx, Ny)] + r * d_in[IX(i1, j0, k1, Nx, Ny)])
(gdb) p i0
$2 = 105
(gdb) p j0
$3 = 129
(gdb) p k1
$4 = 546
(gdb) p Nx
$5 = 258
(gdb) p Ny
$6 = 130
...
(gdb) p i1
$9 = 104

```
